### PR TITLE
Addresses #13 - REST API documentation via OpenAPI

### PR DESCRIPTION
**Pull request by Jamibaraki**
Addition of OpenAPI 3.1 Yaml file describing OIDPlus API.

This initial file has a considerable amount of placeholder data that should be updated, such as: Descriptions.
Contact Info.
URLs.

It omits some data, such as security information.

Some of it is speculative such as: The path variables. The response properties are in an array called 'Response'.

Someone more familiar with the API should check it thoroughly, confirm everything, and make updates where needed.

There is also some repetition in the data, which could be fixed with refs but that should wait until it has been checked.

### CODE REVIEW

**Comment by danielmarschall** [comment]
@Jamibaraki Thank you so much for your great help! I am so glad you could help me with this.

I have added a commit to your pull request and want to ask if you could review it.

The editor https://editor-next.swagger.io/ shows a lot of warnings that "example:" is deprecated and should be replaced by "examples:".

However, when I try that, sometimes either the examples are not displayed in the GUI, and sometimes I get weird errors, such as "examples must be an array".

Just one example, this is what ChatGPT gave me, which is not accepted by Swagger:

```
status_bits:
  type: object
  description: Reserved flags with their descriptions
  additionalProperties:
    type: string
    description: The description of the reserved flag
  examples:
    example1:
      summary: Example with some flags
      value:
        1: "Reserved for flag 1"
        2: "Reserved for flag 2"
        4: "Reserved for flag 4"
        8: "Reserved for flag 8"
```

Can you please help me with handle the example deprecation warnings? Thank you very much! :-)

**Comment by danielmarschall** [comment]
Just for better understanding what `status_bits` does:

The server could reply:

```
{
  "status": 3,
  "status_bits": [
    1: "foo"
    2: "bar"
  ]
}
```

So that the user does understand that status 3 contains the flags foo (1) and bar (2).

**Comment by Jamibaraki** [comment]
I'll try and have a closer look later, but briefly I think the issue is that when you've changed `examples` to `example` you've lost the brackets. 
eg: on line 369 `examples: [-1,1]` becomes `example:0` and it sounds like your changing that to `examples:0` and it doesn't work. 
Try putting the brackets back, so `examples:[0]`

**Comment by danielmarschall** [comment]
Here is how the new feature looks in production:
https://hosted.oidplus.com/viathinksoft/plugins/viathinksoft/publicPages/002_rest_api/swagger-ui/

**Comment by danielmarschall** [comment]
The SVN commit has been synced here: https://github.com/danielmarschall/oidplus/commit/8ec326b4fb92b55946a73a7110b63a1bec33630a
(overwriting your commit https://github.com/danielmarschall/oidplus/commit/a85ab6f8c1461ca4374882b7430625a602431733)

The file api-description.yaml has been renamed to:
https://github.com/danielmarschall/oidplus/blob/master/plugins/viathinksoft/publicPages/000_objects/openapi-3.1.0.yaml

Here is how the new feature looks in production:

- YAML file created on-the-fly: https://hosted.oidplus.com/viathinksoft/plugins/viathinksoft/publicPages/002_rest_api/openapi_yaml.php

- Swagger UI: https://hosted.oidplus.com/viathinksoft/plugins/viathinksoft/publicPages/002_rest_api/swagger-ui/

I am looking forward to your feedback and your idea how to fix the deprecated "example" fields :-)

**Comment by Jamibaraki** [comment]
@danielmarschall Just checking if you need help with this. I checked out the link to your Swagger and it looks like it's outputting OK.

**Comment by danielmarschall** [comment]
@Jamibaraki 

Yes, actually I still need with resolving the deprecation warnings.

For status_bits, this gives a warning:

					 "example":{
					    "1":"Reserved for flag 1",
					    "2":"Reserved for flag 2",
					    "4":"Reserved for flag 4",
					    "8":"Reserved for flag 8"
					 }

But when I change it to:

```
                                 "examples":{
					 "example1":{
					    "1":"Reserved for flag 1",
					    "2":"Reserved for flag 2",
					    "4":"Reserved for flag 4",
					    "8":"Reserved for flag 8"
					 }
                                 }

```

Then I get an error "examples" must be an array.

I tried various things with YAML and JSON but I don't get it to work

Thank you for your help offer!

**Comment by Jamibaraki** [comment]
To make examples an array, use square brackets, like: `examples: [-1,0]`
That example has two elements, but you can just have a single element in if you want. But you still need the brackets to show it's an array.

So to put your object in a single element array, I think this would work:

`examples: [{"1":"Reserved for flag 1","2":"Reserved for flag 2","4":"Reserved for flag 4","8":"Reserved for flag 8"}]`

That's valid at least.

**Comment by danielmarschall** [comment]
Thank you for the quick reply!

**_For the responses:_**

Changing from `example` to `examples` resolves the warning indeed:

```yaml
                  status_bits:
                    type: object
                    description: >-
                      In case status bits (values 1, 2, 4, 8, ...) were included
                      in the status, then they are described in the array
                      status_bits. When programmatically processing a status,
                      please use the bit flags in "status", not the explanation
                      text in "status_bits"!
                    additionalProperties:
                      type: string
                      description: The description of the flag
                    examples:
                      - '1': Reserved for flag 1
                        '2': Reserved for flag 2
                        '4': Reserved for flag 4
                        '8': Reserved for flag 8
```

Unfortunately, Swagger does not show the example then.

This is if I use the deprecated `example`:
image

If changed to `examples` I get this disimprovement:
image

If examples are not shown, maybe I should then explain the status bits in the description instead.

---

The same problem applies for input parameters (which I need to implement today):

When using the deprecated `example`, then I get a deprecation warning, but Swagger shows the example:

```yaml
        - in: path
          name: ns
          schema:
            type: string
            example: "oid example"
          required: true
          description: A namespace managed in OIDplus, such as "oid", "guid", etc.
```

image

When using `examples`, it is valid, but Swagger does not show any example which is a great disimprovement:

```yaml
        - in: path
          name: ns
          schema:
            type: string
            examples:
               - "hello"
               - "world"
          required: true
          description: A namespace managed in OIDplus, such as "oid", "guid", etc.
```

image

---

So I guess, I think I need to decide if I want to deliver a specification with deprecated fields, or deliver a file with valid fields, but have them not displayed in Swagger

**Comment by Jamibaraki** [comment]
It still looks like you don't have the square brackets surrounding the content of your 'examples'.

**Comment by danielmarschall** [comment]
I did try it:

```json
                              "status_bits":{
                                 "type":"object",
                                 "description":"In case status bits (values 1, 2, 4, 8, ...) were included in the status, then they are described in the array status_bits. When programmatically processing a status, please use the bit fl>
                                 "additionalProperties":{
                                    "type":"string",
                                    "description":"The description of the flag"
                                 },
                                 "examples":[{
                                    "1":"Reserved for flag 1",
                                    "2":"Reserved for flag 2",
                                    "4":"Reserved for flag 4",
                                    "8":"Reserved for flag 8"
                                 }]
                              },
```

[Swagger Editor](https://editor-next.swagger.io/) translates this from JSON to YAML:

```yaml
                  status_bits:
                    type: object
                    description: >-
                      In case status bits (values 1, 2, 4, 8, ...) were included
                      in the status, then they are described in the array
                      status_bits. When programmatically processing a status,
                      please use the bit flags in "status", not the explanation
                      text in "status_bits"!
                    additionalProperties:
                      type: string
                      description: The description of the flag xxx
                    examples:
                      - '1': Reserved for flag 1
                        '2': Reserved for flag 2
                        '4': Reserved for flag 4
                        '8': Reserved for flag 8
```

The swagger Editor does not show examples then:
image

and if I try the JSON directly in Swagger UI, the same behavior:
image

**Comment by Jamibaraki** [comment]
It might be the new lines / spacing causing the issue. Try pasting this into it on a single line, replacing the whole existing examples and everything it contains:

`examples: [{"1":"Reserved for flag 1","2":"Reserved for flag 2","4":"Reserved for flag 4","8":"Reserved for flag 8"}]`

**Comment by wehowski** [comment]
As some of the Plugins API Urls (e.g. RDAP Plugin and others) offer custom/dynamically configurable API-URIs, and to avoid those JSON parsing errors I would suggest to generate the OpenAPI JSON/YAML programatically by PHP!?!

This is a library using annotations: https://github.com/zircote/swagger-php
There are other ones, but I must remember/google and find them...
https://openapi-generator.tech/docs/generators/php/

The Webfan API (powered by Fusio API) uses the PSX framework: https://github.com/apioo/psx
It refers to https://www.openapis.org/

**However, the implementation of Swagger/OPenAPI in OIDplus is a great benefit, thank you!!!**

Unfortunatly, my Webfan Swagger currently does not support openapi 3.0.1, but I hackisch dirty quick fixed it until I can update my swagger to include it in the API Explorer: https://api.webfan.de/apps/swagger-ui/?api=registry#/objects

**Comment by danielmarschall** [comment]
@Jamibaraki 
Does not work. I think it is a problem with Swagger UI, so I will contact them. They display "example", but not "examples". My suggestion to them would be that they present at least one example for output parameter, as well as the first example for input parameters (because there can be just one).
So, at the moment, I don't need help with OpenAPI. Thank you so much for helping me with this!

@wehowski 
The OpenAPI file is created on-the-fly.
As an explanation, here is how it works:

1. The plugin defines a JSON template: https://github.com/danielmarschall/oidplus/blob/master/plugins/viathinksoft/publicPages/000_objects/openapi-3.1.0.json
2. The plugin presents its OpenAPI definitions using the `INTF_OID_1_3_6_1_4_1_37476_2_5_2_3_9::restApiInfo()` method: https://github.com/danielmarschall/oidplus/blob/master/plugins/viathinksoft/publicPages/000_objects/OIDplusPagePublicObjects.class.php#L335 as JSON string
3. The RA base plugin merges all JSON files together (only taking `tags` and `paths` taken from the plugin) and fills the other nodes (`openapi`, `info`, `server`, `component`) with the valid OIDplus URL, System Name, administrator email, etc.: https://github.com/danielmarschall/oidplus/blob/master/plugins/viathinksoft/publicPages/002_rest_api/openapi_json.php
4. The Swagger UI displays the output from openapi_json.php . This is the OpenAPI JSON file which displays all REST APIs supported by this OIDplus system.

If you really have a plugin that has dynamic paths, then all you need to do is to implement restApiInfo() and output a dynamic JSON string rather than a static one like I did. This info should then be present in `openapi_json.php` on-the-fly. However, remember:
1. currently only `tags` and `paths` are taken 
2. due to the merging, all plugins must agree on an uniform OpenAPI version. In our case, we choose 3.1.0 , so you must be compatible with that version

**Comment by wehowski** [comment]
I just meant, that you can generate the openapi-3.1.0.json files programatically by php by libraries, this often avoids parsing/template errors and is much easier for developers than to edit an openapi-3.1.0.json file manually?

**Comment by danielmarschall** [comment]
Using a static openapi-3.1.0.json file just was my way to implement this. You don't need a file (and not a temporary file either). It is perfectly fine to write a plugin like this:

	public function restApiInfo(string $kind='html'): string {
		$someOpenApiGeneratorLibrary = new ContosoOpenApiGenerator(...);
		if ($kind === 'openapi-3.1.0-json') {
			return json_encode($someOpenApiGeneratorLibrary->generate());
		} else if ($kind === 'html') {
			throw new OIDplusException(_L('HTML Rest API support has been dropped'), null, 500);
		} else {
			throw new OIDplusException(_L('Invalid REST API information format'), null, 500);
		}
	}

So I think either you use a static file (like me), which is created using an IDE such as Swagger Editor or PhpStorm,
or you use a library to generate it, but then I suggest not creating a file, except if you really need super high performance; in that case you could create a temporary file in userdata/cache/

**Pull request merged**
